config/routes.rb
Rails.application.routes.draw do


    get 'conference/show/:id', to: "conference#show", as: :conference
    get 'conference/show_people/:id', to: "conference#show_people", as: :show_people
    devise_for :users
    resources :papers
    #resources :users


    post 'papers/:id/grade',    to: "papers#rate", as: :paper_rate
    get 'papers/:id/grade',     to: "papers#grade", as: :paper_grade
    post 'papers/:id/skip',     to: "papers#skip", as: :paper_skip
    get 'papers/:id/accept',    to: "papers#accept", as: :paper_accept
    get 'users/login',          to: 'application#login_with_frab',  as: :login_user
    get 'papers/remove_rating/:id', to: "papers#remove_rating", as: :paper_remove_rating
    get 'send_email/:email',    to: "conference#send_email_to", as: :send_email_to
    get 'user/new-account/:id',     to: "conference#create_account", as: :create_account
    patch 'update-account',          to: "conference#update_user",     as: :update_user
    post 'send_email',          to: "conference#send_email", as: :send_email
    post 'mark_paid/:id',           to: "conference#mark_paid", as: :mark_paid
    root 'papers#index'

    get 'payment',            to: "payment#index"
    patch 'update_payment',    to: "payment#update", as: :update

end

app/models/conference.rb
class Conference < ApplicationRecord
  has_many :events
  has_many :conference_users
  has_one :call_for_participation
  has_many :review_metrics

  def number_of_people
    self.events.map{|event| event.event_people.pluck(:person_id)}.flatten.uniq.size
  end

  def number_of_papers
    Paper.all.select{|p| p.event && p.event.conference_id == self.id}.uniq.size
  end

  def number_of_graded_papers
    Paper.all.select{|p| p.event && p.event.conference_id == self.id && p.event.event_ratings.size > 0}.uniq
  end

  def cfp_ended
    self.call_for_participation.end_date < DateTime.now
  end

  def number_of_finished_papers
    Paper.all.select{|p| p.finished?}.size
  end

end

app/controllers/conference_controller.rb
class ConferenceController < ApplicationController

  before_action :check_admin, except: [:create_account, :update_user]

  PRACTICAL_CONST = ["Non-academic Session"]
  ACADEMIC_CONST = ["Paper Presentation", "Special Session"]

  def create_account
    @user = User.find_by(id: params[:id])
  end

  def mark_paid
    @user = User.find_by(id: params[:id])
    if @user && @user.user_adapter
      @user.user_adapter.update(paid: !@user.user_adapter.paid)
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  end

  def update_user
    user = User.find_by(id: params[:id].to_i)
    if user
      user.update(password: params[:user][:password], gdpr: true)
      sign_in(:user, user)
      redirect_to root_path
      return
    else
      redirect_to root_path
      return
    end
  end


  def show
    conference = Conference.find_by(id: params[:id].to_i)
    if conference
      @papers = Paper.all.select{|paper| paper.event && paper.event.conference_id == conference.id}
      if params[:query]
        @papers = @papers.select{|paper|
          (paper.title && paper.title.downcase.include?(params[:query].downcase)) ||
          (paper.description && paper.description.downcase.include?(params[:query].downcase)) ||
          (paper.subtitle && paper.subtitle.downcase.include?(params[:query].downcase))
        }
      end
      if params[:prikaz]
        if params[:prikaz] == "academic"
          @papers = @papers.select{|paper| paper.event.event_type.in?(ACADEMIC_CONST)}
        elsif params[:prikaz] == "practical"
          @papers = @papers.select{|paper| paper.event.event_type.in?(PRACTICAL_CONST)}
        end
      end
    else
      redirect_to root_path
    end
  end

  def send_email_to
    @user = Person.find(params[:email]).user
    @conference = params[:id]
  end

  def send_email
    conference = Conference.find(params[:id])
    ApplicationMailer.with(email: params[:email], title: params[:title], content: params[:msg]).send_email_to.deliver_later
    redirect_to show_people_path(conference.id)
  end

  def show_people
    @conference = Conference.find_by(id: params[:id].to_i)
    if @conference
      if Payment::PAYMENT_ENABLED
        #@people = @conference.events.map{|e| e.event_people.where(event_role: ["submitter","speaker"]).map{|ep| ep.person}.flatten.uniq}.flatten.uniq.compact
        #@people = @people + User.where("counter is not null").map{|u| u.person}.compact
        #@people = @people + Person.where(id: [777,778])
        #@people = @people.sort_by {|obj| obj.id }
        @people = Person.where("user_id is not null").order(:id)
      else
        @people = @conference.events.map{|e| e.event_people.where(event_role: "submitter").map{|ep| ep.person}.flatten.uniq}.flatten.uniq
      end
      if params[:query]
        @people = @people.select{|p|
          (p.first_name && p.first_name.downcase.include?(params[:query].downcase)) ||
          (p.last_name && p.last_name.downcase.include?(params[:query].downcase)) ||
          (p.email && p.email.downcase.include?(params[:query].downcase))
        }
      end
    else
      redirect_to root_path
    end
  end

  private

  def check_admin
    redirect_to root_path unless current_user && current_user.admin?
  end
end

app/helpers/conference_helper.rb
module ConferenceHelper
end

app/views/conference/create_account.html.erb
<%= simple_form_for @user, url: update_user_path do |f| %>
<%= hidden_field_tag "id", @user.id %>
  <main class="form">
    <h5>Setup password for your account</h5>
    <p>Please choose password for your account associated with your email address (<%= @user.email %>). Once you create your account, you will get access to sign up for the Degrowth conference. More information about the confrence can be found on <a href="https://odrast.hr/">this</a> link.

    <section class="forms">
      <%= f.error_notification %>
      <div class="form-inputs">

        <%= f.input :password,
                    label: "Password",
                    required: true,
                    autofocus: true,
                    hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                    input_html: { autocomplete: "new-password" } %>
        <%= f.input :password_confirmation,
                    label: "Confirm your new password",
                    required: true,
                    input_html: { autocomplete: "new-password" } %>
      </div>
      <br>
      <div class="form-actions">
        <%= f.button :submit, "Save and continue" %>
      </div>

<% end %>

app/views/conference/send_email_to.html.erb
<%= simple_form_for "", url: send_email_path do |f| %>
  <main class="form">
    <section class="forms">
      <h4>Send email to user</h4>
          <%= f.input :id, as: :hidden, input_html: {value: @conference} %>
          <%= f.input :email, label: "User email", input_html: {value: @user.email} %>
          <%= f.input :title, label: "Subject" %>
          <%= f.input :msg, label: "E-mail content", as: :text %>
          <%= f.submit "Send" %>
    </section>
  </main>
<% end %>

app/views/conference/show.html.erb
<main>
  <section class="collection">
  </section>
  <%= render partial: "components/search", locals: {path: conference_path(params[:id])} %>

  <section class="collection">
    <%= link_to "Show all participants", show_people_path(params[:id]) %>
    <table>
       <thead>
         <tr>
             <th>Name</th>
             <th>Paper Type</th>
             <th>Status</th>
             <th>Reviewed(Accepted)</th>
             <th>Actions</th>
         </tr>
       </thead>

       <tbody>
         <% @papers.each do |item| %>
           <tr>
             <td><%= item.event.title %></td>
             <td><%= item.event.event_type %></td>
             <td><% if item.finished? %>
               <i class="material-icons">check</i>
             <% else %>
              <i class="material-icons">report</i>
             <% end %>
            </td>
            <td><%= item.event.event_ratings.where(peer: true).size %> (<%= UserAdapter.all.select{|ua| ua.accepted.include?(item.id)}.size %>)</td>
             <td><%= link_to paper_path(item.id) do %>
                 <i class="material-icons">edit</i>
               <% end %>
             </td>
           </tr>
         <% end %>
       </tbody>
     </table>


  </section>
</main>

app/views/conference/show_people.html.erb
<main>
  <section class="collection">
  </section>
  <%= render partial: "components/search", locals: {path: show_people_path(params[:id])} %>

  <section class="collection">
    <%= link_to "Show all papers", conference_path(params[:id]) %>
    <% if Payment::PAYMENT_ENABLED %>
      <table>
         <thead>
           <tr>
              <th>ID</th>
               <th>Name</th>
               <th>Email</th>
               <th>Last offer requested time</th>
               <th>Student ID</th>
               <th>Paid</th>
               <th>Actions</th>
           </tr>
         </thead>

         <tbody>
           <% @people.each do |item| %>
             <tr>
               <td><%= item.user.id %></td>
               <td><%= item.first_name %> <%= item.last_name %></td>
               <td><%= item.user.email %></td>
               <td><%= (!item.user.payment.nil? && !item.user.payment.request_date.nil?) ? "#{item.user.payment.request_date.strftime("%d.%m.%Y")}" : "-" %></td>
               <td><%= (!item.user.payment.nil? && !item.user.payment.document.nil? && item.user.payment.document.normal.url) ? link_to("Picture",item.user.payment.document.normal.url, target: :blank) : "-" %></td>
               <td><% if item.user.user_adapter && item.user.user_adapter.paid %>
                 <i class="material-icons">check</i>
               <% else %>
                <i class="material-icons">report</i>
               <% end %>
              <% if item.user.user_adapter && item.user.user_adapter.paid %>
                <td><%= link_to "Mark as unpaid", mark_paid_path(item.user.id), method: :post %></td>
              <% else %>
                <td><%= link_to "Mark as paid", mark_paid_path(item.user.id), method: :post %></td>
              <% end %>
             </tr>
           <% end %>
         </tbody>
       </table>
    <% else %>
      <table>
         <thead>
           <tr>
               <th>Name</th>
               <th>Email</th>
               <th>Submitted/Reviewed</th>
               <th>Actions</th>
           </tr>
         </thead>

         <tbody>
           <% @people.each do |item| %>
             <tr>
               <td><%= item.first_name %> <%= item.last_name %></td>
               <td><%= item.user.email %></td>
               <% a = item.user.get_papers(@conference).size %>
               <% b = item.user.papers_evaluated(@conference.id) %>
               <% if a*3 <= b %>
                <td style="color:green"><%= a %>/<%= b %></td>
               <% else %>
                <td style="color:red"><%= a %>/<%= b %></td>
              <% end %>
              <td><%= link_to "Send email", send_email_to_path(item.id, id: params[:id]) %></td>
             </tr>
           <% end %>
         </tbody>
       </table>
       <% end %>


  </section>
</main>