config/routes.rb
Rails.application.routes.draw do


    get 'conference/show/:id', to: "conference#show", as: :conference
    get 'conference/show_people/:id', to: "conference#show_people", as: :show_people
    devise_for :users
    resources :papers
    #resources :users


    post 'papers/:id/grade',    to: "papers#rate", as: :paper_rate
    get 'papers/:id/grade',     to: "papers#grade", as: :paper_grade
    post 'papers/:id/skip',     to: "papers#skip", as: :paper_skip
    get 'papers/:id/accept',    to: "papers#accept", as: :paper_accept
    get 'users/login',          to: 'application#login_with_frab',  as: :login_user
    get 'papers/remove_rating/:id', to: "papers#remove_rating", as: :paper_remove_rating
    get 'send_email/:email',    to: "conference#send_email_to", as: :send_email_to
    get 'user/new-account/:id',     to: "conference#create_account", as: :create_account
    patch 'update-account',          to: "conference#update_user",     as: :update_user
    post 'send_email',          to: "conference#send_email", as: :send_email
    post 'mark_paid/:id',           to: "conference#mark_paid", as: :mark_paid
    root 'papers#index'

    get 'payment',            to: "payment#index"
    patch 'update_payment',    to: "payment#update", as: :update

end

app/models/paper.rb
class Paper < ApplicationRecord
  belongs_to :event
  has_many :grades

  SUPPORTED = %w[en de es pt-BR fr zh ru it].freeze

  PRACTICAL_CONST = ["Non-academic Session"]
  ACADEMIC_CONST = ["Paper Presentation", "Special Session"]

  def as_json(options={})
    #options[:methods] = [:is_password]
    #options[:include] = [:event => {:include => {:event_classifiers}}]
    super(:include => [:grades,:event => {:include => [:event_classifiers]}], :methods => [:average_grade])
  end

  def check_paper(conf,user)
    self.event &&
    self.event.conference_id == conf.id &&
    !user.skipped?(self.id) &&
    ((self.event.event_type.in?(ACADEMIC_CONST) && !self.finished_with_accepted?) || (self.event.event_type.in?(PRACTICAL_CONST) && !self.finished_with_accepted?))
  end

  def user_not_coauthor?(user)
    return true if user.email.blank?
    return false if self.event.nil?
    event = self.event
    return false if event.coauthor_1 == user.email || event.coauthor_2 == user.email || event.coauthor_3 == user.email || event.coauthor_4 == user.email || event.coauthor_5 == user.email
    return true
  end

  def average_grade
    avg = 0
    self.grades.each{|g| avg = avg + g.value}
    return avg*1.0/self.grades.size
  end

  def title
    self.event.title if self.event
  end

  def finished_with_accepted?
    return true if self.event.event_ratings.where(peer: true).size >= 3
    total = self.event.event_ratings.where(peer: true).size
    return UserAdapter.all.select{|ua| ua.accepted.include?(self.id)}.size >= 3
  end

  def subtitle
    self.event.subtitle if self.event
  end

  def description
    self.event.description if self.event
  end

  def abstract
    self.event.abstract if self.event
  end


  def finished?
    return false if self.event.nil?
    return self.event.event_ratings.where(peer: true).size >= 3
  end

  def language
    case self.event.language
    when "en"
      "English"
    when "de"
      "German"
    when "es"
      "Spanish"
    when "fr"
      "French"
    when "ru"
      "Russian"
    when "it"
      "Italian"
    when "pt-BR"
      "Portuguese"
    when "zh"
      "Chinese"
    else
      "Not defined"
    end if self.event
  end

  def documents
    self.event.event_attachments.select{|ea| ea.public} if self.event
  end

  def links
    self.event.links if self.event
  end

  def classifiers
    self.event.event_classifiers.map{|ec| ec.classifier}.uniq if self.event
  end

  def event_type
    self.event.event_type if self.event
  end

end

app/controllers/papers_controller.rb
class PapersController < ApplicationController

  #before_action :check_user_role, except: :index

  before_action :check_if_review_done

  def index
    if current_user
      @user_conferences = current_user.conferences#.select{|conference| conference.cfp_ended}
      @related = current_user.get_related_papers
      @related = @related.blank? ? Hash.new : @related
      @crew = current_user && current_user.role != "submitter"
      @admin = current_user && current_user.admin?
    end
  end

  def show
    @item = Paper.find(params[:id])
    @event_rating = EventRating.find_by(person_id: current_user.person.id, event: @item.event, peer: true)
  end

  def accept
    paper = Paper.find(params[:id])
    if paper && current_user.can_accept?(paper.event.conference_id) && !current_user.user_adapter.accepted.include?(paper.id)
      user_adapter = current_user.user_adapter
      user_adapter.accepted << paper.id
      user_adapter.save!
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def remove_rating
    if current_user && current_user.admin?
      event_rating = EventRating.find_by(id: params[:id].to_i, peer: true)
      if event_rating
        event_rating.destroy!
        redirect_to paper_path(Paper.find_by(event_id: event_rating.event.id))
      else
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def rate
    paper = Paper.find(params[:id])
    if paper && !current_user.graded?(paper) && EventRating.where(event: paper.event, person: current_user.person, peer: true).blank?
      conf = paper.event.conference
      total_rating = 0.0
      count = 0
      conf.review_metrics.each do |metric|
        if params[metric.name.to_sym]
          total_rating = total_rating + (params[metric.name.to_sym].to_i/2.0).round(1)
          count = count + 1
        end
      end
      EventRating.create(event: paper.event,peer: true, rating: (total_rating/(count*1.0)).round(1), comment: params[:note],person: current_user.person)
      user_adapter = current_user.user_adapter
      user_adapter.papers_evaluated << paper.id
      if !user_adapter.accepted.include?(paper.id)
        user_adapter.accepted << paper.id
      end
      user_adapter.save!
      redirect_to paper_path(paper)
    else
      redirect_to root_path
    end
  end

  def grade
    @item = Paper.find_by(id: params[:id])
    if @item.nil?
      redirect_to root_path
    end
    @conference = @item.event.conference
  end

  def skip
    paper = Paper.find(params[:id])
    if paper
      adapter = current_user.user_adapter
      if !current_user.skipped?(paper.id)
        adapter.skipped << paper.id
        adapter.save!
      end
      redirect_to root_path
    end
  end

  private

  def check_user_role
    if current_user && current_user.role != "submitter"
      redirect_to root_path
    end
  end

  def check_if_review_done
    if Payment::PAYMENT_ENABLED && current_user && !current_user.admin?
      redirect_to payment_path
    end
  end
end

app/views/papers/grade.html.erb
<main class="item">
  <section>
    <%= link_to conference_path(@item.event.conference.id), class: "waves-effect waves-teal btn-flat btn-small teal lighten-1 white-text" do %>
      Back
    <% end %>
    <br><br>
    <span>Title</span>
    <h3><%= @item.title %></h3>

    <% unless @item.subtitle.blank? %>
      <span>Subtitle</span>
      <p><%= @item.subtitle %></p>
    <% end %>

    <% unless @item.abstract.blank? %>
      <span>Abstract</span>
      <p><%= @item.abstract %></p>
    <% end %>

    <% unless @item.description.blank? %>
      <span>Description</span>
      <p><%= @item.description %></p>
    <% end %>

    <% unless @item.event_type.blank? %>
      <span>Event type</span>
      <p><%= @item.event_type %></p>
    <% end %>

    <% unless @item.classifiers.blank? %>
      <span>Tags</span>
      <p><%= raw @item.classifiers.pluck(:name).join(",") %></p>
    <% end %>


    <br>
  </section>

  <section>
    <%= render partial: "components/rate", locals: {data: @item} %>
  <section>
</main>

app/views/papers/index.html.erb
<main>
  <% if @admin %>
    <h3>Welcome to FRAB Peer Review microservice - Administration</h3>
    <section class="collection">
    </section>
    <% @user_conferences.each do |conference| %>
      <h3><%= conference.title %></h3>
        <section class="collection">
          <p>Number of users: <%= conference.number_of_people%></p>
          <p>Number of papers: <%= conference.number_of_papers%></p>
          <p>Number of reviewed papers: <%= conference.number_of_papers%></p>
          <p>Number of finished papers: <%= conference.number_of_finished_papers %></p>
          <p>Call for participation: <%= conference.call_for_participation.start_date %> to <%= conference.call_for_participation.end_date %></p>
        </section>
    <% end %>
  <% else %>
    <h3>Welcome <%= current_user.full_name %>,</h3>
    <section class="collection">
      <p>Follow the instructions below to review papers submitted in the given conference. If you have any questions or you encounter bugs, feel free to contact us at <a href="mailto:support@odrast.hr">support@odrast.hr</a>  </p>
    </section>


    <% @user_conferences.each do |conference| %>
      <h3><%= conference.title %>  <progress value="<%= current_user.papers_evaluated(conference.id) %>" max="<%= current_user.get_papers(conference.id).size*3 %>"></progress><span id="progress_span"><%= current_user.papers_evaluated(conference.id) %>/<%= current_user.get_papers(conference.id).size*3 %></span></h3>
      <p>You need to review a total of <%= current_user.get_papers(conference.id).size*3 %> papers. You have finished reviewing <%= current_user.papers_evaluated(conference.id) %> papers.</p>

      <section class="cards collection">
        <% @related[conference.id].each do |item| %>
          <%= render partial: "components/card", locals: {data: item, conference: conference} %>
        <% end %>
      </section>

      <% if @related[conference.id].size < current_user.get_papers(conference.id).size*3 %>
        <p>You're out of papers to review. Please contact us for more information.</p>
      <% end %>

      <% if current_user.papers_evaluated(conference.id) == current_user.get_papers(conference.id).size*3 %>
        <p>You have finished the review process. Thank you for participating in peer reviews.</p>
      <% end %>

      <br>
      <br>
    <% end %>
  <% end %>

</main>

app/views/papers/show.html.erb
<main class="item">
  <section>
    <%= link_to conference_path(@item.event.conference.id), class: "waves-effect waves-teal btn-flat btn-small teal lighten-1 white-text" do %>
      Back
    <% end %>
    <br><br>
    <span>Title</span>
    <h3><%= @item.title %></h3>

    <% unless @item.subtitle.blank? %>
      <span>Subtitle</span>
      <p><%= @item.subtitle %></p>
    <% end %>

    <% unless @item.abstract.blank? %>
      <span>Abstract</span>
      <p><%= @item.abstract %></p>
    <% end %>

    <% unless @item.description.blank? %>
      <span>Description</span>
      <p><%= @item.description %></p>
    <% end %>

    <% unless @item.event_type.blank? %>
      <span>Event type</span>
      <p><%= @item.event_type %></p>
    <% end %>

    <% unless @item.event.track.blank? %>
      <span>Theme</span>
      <p><%= @item.event.track.name %></p>
    <% end %>

    <% unless @item.classifiers.blank? %>
      <span>Tags</span>
      <p><%= raw @item.classifiers.pluck(:name).join(",") %></p>
    <% end %>

    <br>
    <br>
    <% if current_user && current_user.admin? %>
      <h5>Reviews</h5>
      <table>
         <thead>
           <tr>
               <th>User</th>
               <th>Rating</th>
               <th>Comment</th>
               <th>Actions</th>
           </tr>
         </thead>
         <tbody>
           <% @item.event.event_ratings.where(peer: true).each do |event_rating| %>
             <tr>
               <td><%= event_rating.person.public_name %></td>
               <td><%= event_rating.rating %></td>
               <td><%= event_rating.comment %></td>
               <td><%= link_to paper_remove_rating_path(event_rating.id) do %>
                   <i class="material-icons">delete</i>
                 <% end %>
               </td>
             </tr>
           <% end %>
         </tbody>
       </table>
       <br>
       <% if !current_user.user_adapter.papers_evaluated.include?(@item.id) %>
         <%= link_to paper_grade_path(@item.id, admin: true), class: "waves-effect waves-teal btn-flat btn-small teal lighten-1 white-text" do %>
           Review paper
         <% end %>
       <% end %>
       <br><br>
       <% if !UserAdapter.all.select{|ua| ua.accepted.include?(@item.id) && !ua.papers_evaluated.include?(@item.id)}.blank? %>
         <h5>People who accepted the paper but didn't review it</h5>
         <table>
            <thead>
              <tr>
                <th>User</th>
                <th>Email</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% UserAdapter.all.select{|ua| ua.accepted.include?(@item.id) && !ua.papers_evaluated.include?(@item.id)}.each do |user_adapter| %>
                <tr>
                  <td><%= user_adapter.user.person.public_name %></td>
                  <td><%= user_adapter.user.email %></td>
                  <td><%= link_to "Send email", send_email_to_path(email: user_adapter.user.person.id, id: @item.event.conference.id) %>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
    <% else %>
      <% if @event_rating %>
        <% unless @event_rating.rating.blank? %>
          <div class="slidecontainer">
            <label>Average number of points from your review</label>
            <div class="slider_grade">
              <span id="sloder_span_bad">poor</span>
              <input type="range" name="value" min="1" max="10" value="<%= @event_rating.rating*2 %>" class="slider" id="sloder_disabled" disabled>
              <span id="sloder_span">excellent</span>
            </div>
          </div>
        <% end %>
        <% unless @event_rating.comment.blank? %>
          <span>Your note</span>
          <p><%= raw @event_rating.comment %></p>
        <% end %>
      <% end %>
    <% end %>
  </section>

</main>